Task-38523 : Add external tag in agenda event and fix user popover
exoplatform/agenda pull request #156
Opened 2020-12-25 16:01 UTC by ahmadmido

2021-01-04 16:01 UTC, azayati requested changes
See review

2021-01-04 16:01 UTC, azayati commented on agenda-webapps/src/main/webapp/vue-app/agenda-common/components/event/view/AgendaEventAttendeeItem.vue
> +      return this.attendee.identity.space ? this.attendee.identity.space.displayName : this.attendee.identity.profile ? this.fullName : '';
```suggestion
      return this.attendee.identity.space ? this.attendee.identity.space.displayName : this.attendee.identity.profile ? this.attendeeFullName : '';
```

2021-01-05 11:01 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2021-01-06 15:02 UTC, rdenarie approved these changes

2021-01-06 16:59 UTC, merged