Task-42704: manager can create event
exoplatform/agenda pull request #320
Opened 2021-04-12 08:05 UTC by hassenelkamel-exo

**Current behavior:** when set a member as redactor, manager cannot create event.
**new Behavior:** Manager can create events

2021-04-12 12:32 UTC, azayati approved these changes
LGTM after QA validation

2021-04-12 12:35 UTC, azayati requested changes
Unit test to be added

2021-04-12 16:37 UTC, azayati requested changes
See review

2021-04-12 16:37 UTC, azayati commented on agenda-services/src/main/java/org/exoplatform/agenda/util/Utils.java
> +      return (!spaceHasARedactor || isRedactor || isManager) && (superManager || isMember);
```suggestion
      return (!spaceHasARedactor || isRedactor || isManager || superManager) && isMember;
```

2021-04-12 16:51 UTC, boubaker commented on agenda-services/src/main/java/org/exoplatform/agenda/util/Utils.java
> +      return (!spaceHasARedactor || isRedactor || isManager || superManager) && isMember;
```
      if (spaceService.isSuperManager(userIdentity.getRemoteId())) {
        return true;
      } else if(space == null) {
        return false;
      }
      Space space = spaceService.getSpaceByPrettyName(requestedOwner.getRemoteId());
      boolean isManager = spaceService.isManager(space, userIdentity.getRemoteId());
      boolean isMember = spaceService.isMember(space, userIdentity.getRemoteId());
      boolean isRedactor = spaceService.isRedactor(space, userIdentity.getRemoteId());
      boolean spaceHasARedactor = space.getRedactors() != null && space.getRedactors().length > 0;
      return isMember && (!spaceHasARedactor || isRedactor || isManager);
```

2021-04-12 17:43 UTC, boubaker commented on agenda-services/src/test/java/org/exoplatform/agenda/service/BaseAgendaEventTest.java
> +    String displayName1 = "testSpaceAgenda1" + RandomUtils.nextInt();
why adding new space ?

2021-04-13 08:10 UTC, hassenelkamel-exo commented on agenda-services/src/test/java/org/exoplatform/agenda/service/BaseAgendaEventTest.java
> +    String displayName1 = "testSpaceAgenda1" + RandomUtils.nextInt();
i remove it,

2021-04-13 08:23 UTC, azayati approved these changes
LGTM

2021-04-13 10:00 UTC, merged