feat : reorganize application registry list - EXO-61480 - Meeds-io/MPIs#37
exoplatform/agenda pull request #517
Opened 2023-01-04 10:24 UTC by sofyenne

This change is going to add the agenda timeline under the tools application category

2023-01-05 15:50 UTC, azayati requested changes

2023-01-05 15:50 UTC, azayati commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/application-registry-configuration.xml
> +                      <field name="contentId"><string>agenda/AgendaTimeline</string></field>
separate the tags

2023-01-05 15:50 UTC, azayati commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/application-registry-configuration.xml
> +                          <value><string>*:/platform/users</string></value>
separate the tags

2023-01-05 17:29 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 18:22 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-06 11:23 UTC, azayati approved these changes
LGTM

2023-01-06 11:24 UTC, merged