feat: Replace Web Notification rendering engine from gtmpl to Vue - EXO-66404
exoplatform/agenda pull request #578
Opened 2023-10-05 15:54 UTC by rdenarie

This change will allow to not having a gtmpl template associated for some Web Notifications to use Frontend side display instead. This will ensure a better UX, evolutivity and maintainability.

2023-10-05 17:09 UTC, ahamdi requested changes

2023-10-05 17:09 UTC, ahamdi commented on agenda-services/src/main/java/org/exoplatform/agenda/util/NotificationUtils.java
> +  private static final String                                 STORED_PARAMETER_EVENT_IS_CREATOR = "isCreator";
Could you format this line ?

2023-10-05 17:09 UTC, ahamdi commented on agenda-webapps/src/main/webapp/vue-app/agenda-notifications/components/AgendaEventPlugin.vue
> +        message = this.$t('Notification.agenda.event.created', {0: `<span class="font-weight-bold">${eventTitle}</span>`, 1: `<a class="space-name font-weight-bold">${agendaName}</a>`});
We may have a dedicated function for the block inside those if/else as it is repeated, WDYT ?

2023-10-05 17:09 UTC, ahamdi commented on agenda-webapps/src/main/webapp/vue-app/agenda-notifications/components/EventReminderPlugin.vue
> +    console.log(this.notification);
Could you remove this logging statement ?

2023-10-06 12:54 UTC, rdenarie commented on agenda-services/src/main/java/org/exoplatform/agenda/util/NotificationUtils.java
> +  private static final String                                 STORED_PARAMETER_EVENT_IS_CREATOR = "isCreator";
done

2023-10-06 12:54 UTC, rdenarie commented on agenda-webapps/src/main/webapp/vue-app/agenda-notifications/components/AgendaEventPlugin.vue
> +        message = this.$t('Notification.agenda.event.created', {0: `<span class="font-weight-bold">${eventTitle}</span>`, 1: `<a class="space-name font-weight-bold">${agendaName}</a>`});
I am unable to completly remove the if else.  I reduce the code duplication by using a dedicated function

2023-10-06 12:54 UTC, rdenarie commented on agenda-webapps/src/main/webapp/vue-app/agenda-notifications/components/EventReminderPlugin.vue
> +    console.log(this.notification);
done

2023-10-06 13:19 UTC, ahamdi approved these changes
LGTM

2023-10-06 13:19 UTC, merged