Task-35816: Add agenda space template configuration
exoplatform/agenda pull request #60
Opened 2020-10-26 15:22 UTC by AzmiTouil

Add agenda as space default application.

2020-10-26 19:46 UTC, azayati requested changes
See review

2020-10-26 19:46 UTC, azayati commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/spaces-templates-configuration.xml
> +                      <string>Agenda</string>
```suggestion
                      <string>agenda</string>
```
In all file

2020-10-27 08:31 UTC, AzmiTouil commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/spaces-templates-configuration.xml
> +                      <string>Agenda</string>
Done !

2020-10-27 09:00 UTC, azayati submitted a review, later dismissed
PR approved, merge waiting after cherry pick on FT branch and getting the GO from QA

2020-10-27 10:25 UTC, boubaker commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/spaces-templates-configuration.xml
> +    Copyright (C) 2003-2010 eXo Platform SAS.
2020

2020-10-27 11:22 UTC, AzmiTouil commented on agenda-webapps/src/main/webapp/WEB-INF/conf/agenda/spaces-templates-configuration.xml
> +    Copyright (C) 2003-2010 eXo Platform SAS.
Done !

2020-10-27 11:48 UTC, azayati approved these changes
LGTM

2020-10-27 11:59 UTC, merged